#!/bin/bash

echo $1

if [ -d "/home/alex/.daedalus" ]; then
    chmod -R +w /home/alex/.daedalus
    sudo rm -rf /home/alex/.local/bin/daedalus* /home/alex/.daedalus
    sudo rm -f /home/alex/.local/share/applications/Daedalus*.desktop
    echo "deleted"
fi

# Install
mkdir -p /home/alex/.daedalus
sudo chmod -R 757 /home/alex/.daedalus
sudo chmod -R 757 /home/alex/.local

sudo bash $1

sudo chmod -R 757 /home/alex/.daedalus
sudo chmod -R 757 /home/alex/.local
